### ISSUE TITLE
browsersync integration

### ISSUE THREAD

**Issue by cazacugmihai** [voidberg/webpack-angularjs-lazyload#1]
Hi,

Can you integrate also [browsersync](http://www.browsersync.io) in this boilerplate?

Thanks!

**Comment by cazacugmihai** [comment]
I'm new to webpack. It seems that all I have to do is to append " --inline" to the "start" script (in order to remove also the "App ready. " message).

**Comment by voidberg** [comment]
Hi Mihai,

I've got BrowserSync integrated in the boilerplate available here: https://github.com/voidberg/webpack-angularjs
