### ISSUE TITLE
Angular Component Router $router: Unkown Provider Error

### ISSUE THREAD

**Issue by liasrose** [voidberg/webpack-angularjs-lazyload#2]
Hi, maybe you could help me :)

I am going crazy about my Error. I use the AngularJS Component Router with webpack and oclazyload.

I am injecting the dependencies, and debugging shows it also reaches my $router. And without webpack, everythig worked fine.

My Code: 
` app.controller('appController',['$router', '$ocLazyLoad', function ($router, $ocLazyLoad) {

```
$router.config([
    {path: '/', name: 'Home', component: 'home', usaAsDefault: true},

    //Heroes Route
    {
        path: '/heroes/...',
        name: 'Heroes',
        loader: function () {
            // lazy load Heroes
            return $ocLazyLoad.load([require('../dist/heroes.bundle.js')])
                .then(function () {
                    return 'heroes';
                });
        }
    },`
```

I don't know what to do anymore...

**Comment by voidberg** [comment]
Could you create a small repo exhibiting the problem so I can test?

**Comment by liasrose** [comment]
I have this plunker: https://plnkr.co/edit/3PzmVhVkL2iHQDBqKiMt?p=info

**Comment by liasrose** [comment]
changing $router to $rootRouter solved the issue
